const animInstructions = [
    {
      "property": "offsetX",
      "from": "500",
      "to": "-3000",
      "duration": 5000,
      "objectId": "27",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 0
    },
    {
      "property": "offsetY",
      "from": "0",
      "to": "-94",
      "duration": 5000,
      "objectId": "27",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 0
    },
    {
      "property": "tiltV",
      "from": "-150000",
      "to": 0,
      "duration": 5000,
      "objectId": "27",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 0
    },
    {
      "property": "rotation",
      "from": "165000",
      "to": "0",
      "duration": 1429,
      "objectId": "27",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 0
    },
    // {
    //   "property": "zoomX",
    //   "from": "6500",
    //   "to": "8500",
    //   "duration": 5000,
    //   "objectId": "27",
    //   "sizeMode": "1",
    //   "lockAR": 1,
    //   "timestamp": 1650
    // },
    // {
    //   "property": "zoomY",
    //   "from": "6500",
    //   "to": "8500",
    //   "duration": 5000,
    //   "objectId": "27",
    //   "sizeMode": "1",
    //   "lockAR": 1,
    //   "timestamp": 1650
    // },
    {
      "property": "offsetX",
      "from": "39",
      "to": "-438",
      "duration": 6000.0000000000002,
      "objectId": "27",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 1650
    },
    {
      "property": "offsetY",
      "from": "-94",
      "to": "-165",
      "duration": 6000.0000000000002,
      "objectId": "27",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 1650
    },
    {
      "property": "rotation",
      "from": "0",
      "to": "7000",
      "duration": 6000.0000000000002,
      "objectId": "27",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 7000
    },
    {
      "property": "offsetX",
      "from": "-438",
      "to": "523",
      "duration": 7000,
      "objectId": "27",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 7750
    },
    {
      "property": "offsetY",
      "from": "-165",
      "to": "10000",
      "duration": 7000,
      "objectId": "27",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 4750
    },
    {
      "property": "offsetX",
      "from": "500",
      "to": "-3000",
      "duration": 5000,
      "objectId": "28",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 0
    },
    {
      "property": "offsetY",
      "from": "0",
      "to": "-94",
      "duration": 5000,
      "objectId": "28",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 0
    },
    {
      "property": "tiltV",
      "from": "-150000",
      "to": 0,
      "duration": 5000,
      "objectId": "28",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 0
    },
    {
      "property": "rotation",
      "from": "165000",
      "to": "0",
      "duration": 1429,
      "objectId": "28",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 0
    },
    // {
    //   "property": "zoomX",
    //   "from": "6500",
    //   "to": "8500",
    //   "duration": 5000,
    //   "objectId": "28",
    //   "sizeMode": "1",
    //   "lockAR": 1,
    //   "timestamp": 1650
    // },
    // {
    //   "property": "zoomY",
    //   "from": "6500",
    //   "to": "8500",
    //   "duration": 5000,
    //   "objectId": "28",
    //   "sizeMode": "1",
    //   "lockAR": 1,
    //   "timestamp": 1650
    // },
    {
      "property": "offsetX",
      "from": "39",
      "to": "-438",
      "duration": 6000.0000000000002,
      "objectId": "28",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 1650
    },
    {
      "property": "offsetY",
      "from": "-94",
      "to": "-165",
      "duration": 6000.0000000000002,
      "objectId": "28",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 1650
    },
    {
      "property": "rotation",
      "from": "0",
      "to": "7000",
      "duration": 6000.0000000000002,
      "objectId": "28",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 7000
    },
    {
      "property": "offsetX",
      "from": "-438",
      "to": "523",
      "duration": 7000,
      "objectId": "28",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 7750
    },
    {
      "property": "offsetY",
      "from": "-165",
      "to": "10000",
      "duration": 7000,
      "objectId": "28",
      "sizeMode": "1",
      "lockAR": 1,
      "timestamp": 4750
    },
    // {
    //   property: "zoomX",
    //   from: "6500",
    //   to: "8500",
    //   duration: 2418,
    //   objectId: "29",
    //   sizeMode: "1",
    //   lockAR: 1,
    //   timestamp: 10000,
    // },
    // {
    //   property: "zoomY",
    //   from: "6500",
    //   to: "8500",
    //   duration: 2418,
    //   objectId: "29",
    //   sizeMode: "1",
    //   lockAR: 1,
    //   timestamp: 10000,
    // },
    {
      property: "offsetX",
      from: "400",
      to: "-600",
      duration: 2418,
      objectId: "29",
      sizeMode: "1",
      lockAR: 1,
      timestamp: 8000,
    },
    {
      property: "offsetY",
      from: "23",
      to: "-260",
      duration: 2418,
      objectId: "29",
      sizeMode: "1",
      lockAR: 1,
      timestamp: 8000,
    },
    {
      property: "rotation",
      from: "0",
      to: "-6000",
      duration: 2418,
      objectId: "29",
      sizeMode: "1",
      lockAR: 1,
      timestamp: 10000,
    },
    {
      property: "timeSegment",
      from: "2",
      to: "3",
      duration: 1925,
      objectId: "29",
      sizeMode: "1",
      lockAR: 1,
      timestamp: 12000,
    },
    {
      property: "timeSegment",
      from: "2",
      to: "3",
      duration: 1925,
      objectId: "29",
      sizeMode: "1",
      lockAR: 1,
      timestamp: 9000,
    },
    {
      property: "offsetX",
      from: "400",
      to: "-600",
      duration: 2418,
      objectId: "30",
      sizeMode: "1",
      lockAR: 1,
      timestamp: 3000,
    },
    {
      property: "offsetY",
      from: "23",
      to: "-260",
      duration: 2418,
      objectId: "30",
      sizeMode: "1",
      lockAR: 1,
      timestamp: 8000,
    },
    {
      property: "rotation",
      from: "0",
      to: "-6000",
      duration: 2418,
      objectId: "30",
      sizeMode: "1",
      lockAR: 1,
      timestamp: 10000,
    },
    {
      property: "timeSegment",
      from: "2",
      to: "3",
      duration: 1925,
      objectId: "30",
      sizeMode: "1",
      lockAR: 1,
      timestamp: 12000,
    },
    {
      property: "timeSegment",
      from: "2",
      to: "3",
      duration: 1925,
      objectId: "30",
      sizeMode: "1",
      lockAR: 1,
      timestamp: 9000,
    },
  ];